version: '3.8'
services:
  backend:
    container_name: bookmarks-backend
    image: bookmarks-backend-prod:1.0.0
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - shared-network
    depends_on:
      - postgres

  # client:
  #   container_name: bookmarks-client
  #   image: bookmarks-client-prod:1.0.0
  #   restart: unless-stopped
  #   build:
  #     context: client
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - shared-network
  #   depends_on:
  #     - backend

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=bookmarks
      - POSTGRES_USER=danila
      - POSTGRES_PASSWORD=danila
    ports:
      - 5432:5432
    networks:
      - shared-network
    volumes:
      - db:/var/lib/postgres

networks:
  shared-network:

volumes:
  db:
