version: '3.8'

services:
  db:
    image: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=danila
      - POSTGRES_PASSWORD=danila
      - POSTGRES_DB=bookmarks
    expose:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - bookmarks_network

  backend:
    depends_on:
      - db
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    expose:
      - 5000
    environment:
      - DB_HOST=db
    stdin_open: true
    tty: true
    networks:
      - bookmarks_network

  client:
    depends_on:
      - backend
    build: ./client
    restart: unless-stopped
    expose:
      - 5001
    networks:
      - bookmarks_network

  nginx:
    depends_on:
      - client
      - backend
    restart: always # because it is routing traffic to our entire app
    build: ./nginx
    ports:
      - '80:80'
    networks:
      - bookmarks_network

volumes:
  postgres:

networks:
  bookmarks_network:
    bridge:
