version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  client:
    build: ./client
    container_name: client
    ports:
      - '8080:8080'
    depends_on:
      - backend
    networks:
      - public

  postgres:
    image: postgres:alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: 'bookmarks'
      POSTGRES_USER: 'danila'
      POSTGRES_PASSWORD: 'danila'
    ports:
      - '5432:5432'
